bin/Actividad1A: Actividad1A.cpp
	mkdir -p bin
	g++ -o bin/Actividad1A Actividad1A.cpp
	
Actividad1A: bin/Actividad1A
	./bin/Actividad1A

bin/Actividad1B: Actividad1B.cpp
	mkdir -p bin
	g++ -o bin/Actividad1B Actividad1B.cpp
	
Actividad1B: bin/Actividad1B
	./bin/Actividad1B

bin/Actividad2: Actividad2.cpp
	mkdir -p bin
	g++ -o bin/Actividad2 Actividad2.cpp
	
Actividad2: bin/Actividad2
	./bin/Actividad2
	
clean:
	rm -r bin 
